# Generated by Django 4.2.7 on 2026-03-03 23:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OffreEmploiSaisonnier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('type_travail', models.CharField(max_length=100, verbose_name='Type de travail')),
                ('description', models.TextField(verbose_name='Description')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(verbose_name='Date de fin')),
                ('salaire_horaire', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Salaire horaire (FCFA)')),
                ('nombre_postes', models.IntegerField(verbose_name='Nombre de postes')),
                ('postes_pourvus', models.IntegerField(default=0, verbose_name='Postes pourvus')),
                ('statut', models.CharField(choices=[('OUVERTE', 'Ouverte'), ('POURVUE', 'Pourvue'), ('EXPIREE', 'Expirée')], default='OUVERTE', max_length=20, verbose_name='Statut')),
                ('canton', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locations.canton', verbose_name='Canton')),
                ('exploitant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offres_emploi', to=settings.AUTH_USER_MODEL, verbose_name='Exploitant')),
            ],
            options={
                'verbose_name': "Offre d'emploi saisonnier",
                'verbose_name_plural': "Offres d'emploi saisonnier",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContratSaisonnier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(verbose_name='Date de fin')),
                ('salaire_horaire', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Salaire horaire (FCFA)')),
                ('statut', models.CharField(choices=[('SIGNE', 'Signé'), ('EN_COURS', 'En cours'), ('TERMINE', 'Terminé'), ('ANNULE', 'Annulé')], default='SIGNE', max_length=20, verbose_name='Statut')),
                ('exploitant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contrats_exploitant', to=settings.AUTH_USER_MODEL, verbose_name='Exploitant')),
                ('offre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jobs.offreemploisaisonnier', verbose_name='Offre')),
                ('ouvrier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contrats_ouvrier', to=settings.AUTH_USER_MODEL, verbose_name='Ouvrier')),
            ],
            options={
                'verbose_name': 'Contrat saisonnier',
                'verbose_name_plural': 'Contrats saisonniers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HeuresTravaillees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('date', models.DateField(verbose_name='Date')),
                ('heures', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Heures')),
                ('statut_validation', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDEE', 'Validée'), ('CONTESTEE', 'Contestée')], default='EN_ATTENTE', max_length=20, verbose_name='Statut de validation')),
                ('montant_calcule', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant calculé')),
                ('contrat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heures', to='jobs.contratsaisonnier', verbose_name='Contrat')),
            ],
            options={
                'verbose_name': 'Heures travaillées',
                'verbose_name_plural': 'Heures travaillées',
                'ordering': ['-date'],
                'unique_together': {('contrat', 'date')},
            },
        ),
    ]
