# Generated by Django 4.2.7 on 2026-03-07 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("locations", "0001_initial"),
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="offreemploisaisonnier",
            name="est_collective",
            field=models.BooleanField(default=False, verbose_name="Issue d'une annonce collective"),
        ),
        migrations.CreateModel(
            name="AnnonceCollective",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Date de création")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Date de modification")),
                ("type_travail", models.CharField(max_length=100, verbose_name="Type de travail")),
                ("description", models.TextField(verbose_name="Description")),
                ("date_debut", models.DateField(verbose_name="Date de début des travaux")),
                ("date_fin", models.DateField(verbose_name="Date de fin des travaux")),
                (
                    "salaire_horaire",
                    models.DecimalField(decimal_places=2, max_digits=8, verbose_name="Salaire horaire proposé (FCFA)"),
                ),
                ("nombre_postes", models.IntegerField(verbose_name="Nombre de postes souhaités")),
                (
                    "superficie_cumulee",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="Superficie cumulée (ha)"
                    ),
                ),
                (
                    "seuil_hectares",
                    models.DecimalField(decimal_places=2, default=10, max_digits=10, verbose_name="Seuil requis (ha)"),
                ),
                ("date_expiration", models.DateTimeField(verbose_name="Date d'expiration")),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("EN_ATTENTE", "En attente de participants"),
                            ("VALIDEE", "Quota atteint — publiée"),
                            ("EXPIREE", "Expirée — quota non atteint"),
                            ("ANNULEE", "Annulée"),
                        ],
                        default="EN_ATTENTE",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "canton",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="locations.canton", verbose_name="Canton"
                    ),
                ),
                (
                    "createur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="annonces_creees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créateur",
                    ),
                ),
                (
                    "offre_generee",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="annonce_source",
                        to="jobs.offreemploisaisonnier",
                        verbose_name="Offre générée",
                    ),
                ),
            ],
            options={
                "verbose_name": "Annonce collective",
                "verbose_name_plural": "Annonces collectives",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ParticipationAnnonce",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Date de création")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Date de modification")),
                (
                    "superficie_apportee",
                    models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Superficie apportée (ha)"),
                ),
                (
                    "annonce",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participations",
                        to="jobs.annoncecollective",
                        verbose_name="Annonce",
                    ),
                ),
                (
                    "exploitant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="participations_annonces",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Exploitant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Participation à annonce",
                "verbose_name_plural": "Participations aux annonces",
                "unique_together": {("annonce", "exploitant")},
            },
        ),
    ]
