# Generated by Django 4.2.7 on 2026-03-08 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("locations", "0001_initial"),
        ("jobs", "0002_offreemploisaisonnier_est_collective_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnnonceOuvrier",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Date de création")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Date de modification")),
                ("titre", models.CharField(max_length=200, verbose_name="Titre de l'annonce")),
                (
                    "description",
                    models.TextField(
                        help_text="Décrivez vos compétences et votre expérience", verbose_name="Description"
                    ),
                ),
                (
                    "competences",
                    models.JSONField(
                        default=list, help_text="Liste des types de travaux maîtrisés", verbose_name="Compétences"
                    ),
                ),
                (
                    "tarif_horaire_min",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="Tarif horaire minimum souhaité (FCFA)"
                    ),
                ),
                ("date_disponibilite_debut", models.DateField(verbose_name="Disponible à partir du")),
                (
                    "date_disponibilite_fin",
                    models.DateField(blank=True, null=True, verbose_name="Disponible jusqu'au (optionnel)"),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("INACTIVE", "Inactive"), ("EXPIREE", "Expirée")],
                        default="ACTIVE",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                ("date_expiration", models.DateTimeField(blank=True, null=True, verbose_name="Date d'expiration")),
                (
                    "cantons_disponibles",
                    models.ManyToManyField(
                        related_name="annonces_ouvriers",
                        to="locations.canton",
                        verbose_name="Cantons où vous êtes disponible",
                    ),
                ),
                (
                    "ouvrier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="annonces_ouvrier",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Ouvrier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Annonce d'ouvrier",
                "verbose_name_plural": "Annonces d'ouvriers",
                "ordering": ["-created_at"],
            },
        ),
    ]
