# Generated by Django 4.2.7 on 2026-03-08 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0003_annonceouvrier"),
    ]

    operations = [
        migrations.AddField(
            model_name="annonceouvrier",
            name="equipe_complete",
            field=models.BooleanField(default=False, verbose_name="Équipe de 8 personnes complète"),
        ),
        migrations.AddField(
            model_name="annonceouvrier",
            name="membres_equipe",
            field=models.JSONField(
                default=list,
                help_text="Liste des 7 autres membres (nom, prénom, téléphone)",
                verbose_name="Membres de l'équipe",
            ),
        ),
        migrations.AddField(
            model_name="annonceouvrier",
            name="membres_rejoints",
            field=models.JSONField(
                default=list,
                help_text="Liste des ouvriers ayant rejoint l'annonce collective",
                verbose_name="Membres ayant rejoint",
            ),
        ),
        migrations.AddField(
            model_name="annonceouvrier",
            name="nb_membres_actuels",
            field=models.IntegerField(default=1, verbose_name="Nombre de membres actuels"),
        ),
        migrations.AddField(
            model_name="annonceouvrier",
            name="type_annonce",
            field=models.CharField(
                choices=[
                    ("INDIVIDUELLE", "Individuelle - Équipe complète"),
                    ("COLLECTIVE", "Collective - Recrutement d'équipe"),
                ],
                default="INDIVIDUELLE",
                max_length=20,
                verbose_name="Type d'annonce",
            ),
        ),
        migrations.AlterField(
            model_name="annonceouvrier",
            name="statut",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("INACTIVE", "Inactive"),
                    ("EXPIREE", "Expirée"),
                    ("EN_ATTENTE", "En attente d'équipe"),
                    ("VALIDEE", "Équipe complète"),
                ],
                default="ACTIVE",
                max_length=20,
                verbose_name="Statut",
            ),
        ),
    ]
