# Generated by Django 4.2.7 on 2026-03-08 17:44

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Categorie",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nom", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField(blank=True)),
                ("icone", models.CharField(default="📚", max_length=50)),
                ("ordre", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Catégorie",
                "verbose_name_plural": "Catégories",
                "ordering": ["ordre", "nom"],
            },
        ),
        migrations.CreateModel(
            name="ChoixReponse",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("texte", models.CharField(max_length=500)),
                ("est_correct", models.BooleanField(default=False)),
                ("ordre", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Choix de réponse",
                "verbose_name_plural": "Choix de réponses",
                "ordering": ["ordre"],
            },
        ),
        migrations.CreateModel(
            name="Cours",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("titre", models.CharField(max_length=255)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField()),
                (
                    "type_cours",
                    models.CharField(
                        choices=[
                            ("VIDEO", "Vidéo YouTube"),
                            ("LIVESTREAM", "Cours en direct"),
                            ("PLAYLIST", "Playlist YouTube"),
                        ],
                        default="VIDEO",
                        max_length=20,
                    ),
                ),
                (
                    "niveau",
                    models.CharField(
                        choices=[("DEBUTANT", "Débutant"), ("INTERMEDIAIRE", "Intermédiaire"), ("AVANCE", "Avancé")],
                        default="DEBUTANT",
                        max_length=20,
                    ),
                ),
                (
                    "youtube_url",
                    models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()]),
                ),
                ("youtube_video_id", models.CharField(blank=True, max_length=50)),
                ("duree_minutes", models.IntegerField(default=0, help_text="Durée en minutes")),
                ("google_meet_url", models.URLField(blank=True, null=True)),
                ("date_livestream", models.DateTimeField(blank=True, null=True)),
                ("duree_livestream_minutes", models.IntegerField(default=60)),
                ("thumbnail", models.URLField(blank=True)),
                ("est_gratuit", models.BooleanField(default=True)),
                ("prix", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("transcription", models.TextField(blank=True, help_text="Transcription de la vidéo")),
                ("resume_ai", models.TextField(blank=True, help_text="Résumé généré par AI")),
                ("vues", models.IntegerField(default=0)),
                ("est_publie", models.BooleanField(default=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
                (
                    "categorie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="cours", to="elearning.categorie"
                    ),
                ),
                (
                    "instructeur",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cours_crees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Cours",
                "verbose_name_plural": "Cours",
                "ordering": ["-date_creation"],
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("texte", models.TextField()),
                (
                    "type_question",
                    models.CharField(
                        choices=[("QCM", "Choix multiple"), ("VRAI_FAUX", "Vrai/Faux"), ("TEXTE", "Réponse courte")],
                        default="QCM",
                        max_length=20,
                    ),
                ),
                ("points", models.IntegerField(default=1)),
                ("ordre", models.IntegerField(default=0)),
                ("explication", models.TextField(blank=True, help_text="Explication de la réponse correcte")),
            ],
            options={
                "verbose_name": "Question",
                "verbose_name_plural": "Questions",
                "ordering": ["ordre"],
            },
        ),
        migrations.CreateModel(
            name="Quiz",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("titre", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("duree_minutes", models.IntegerField(default=10)),
                (
                    "note_passage",
                    models.IntegerField(
                        default=60,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("est_actif", models.BooleanField(default=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "cours",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="quiz", to="elearning.cours"
                    ),
                ),
            ],
            options={
                "verbose_name": "Quiz",
                "verbose_name_plural": "Quiz",
            },
        ),
        migrations.CreateModel(
            name="TentativeQuiz",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("score", models.IntegerField(default=0)),
                ("score_pourcentage", models.IntegerField(default=0)),
                ("est_reussi", models.BooleanField(default=False)),
                ("date_debut", models.DateTimeField(auto_now_add=True)),
                ("date_fin", models.DateTimeField(blank=True, null=True)),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="tentatives", to="elearning.quiz"
                    ),
                ),
                (
                    "utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tentatives_quiz",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Tentative de quiz",
                "verbose_name_plural": "Tentatives de quiz",
                "ordering": ["-date_debut"],
            },
        ),
        migrations.CreateModel(
            name="ReponseUtilisateur",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("reponse_texte", models.TextField(blank=True)),
                ("est_correct", models.BooleanField(default=False)),
                ("points_obtenus", models.IntegerField(default=0)),
                (
                    "choix_selectionne",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="elearning.choixreponse"
                    ),
                ),
                ("question", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="elearning.question")),
                (
                    "tentative",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reponses",
                        to="elearning.tentativequiz",
                    ),
                ),
            ],
            options={
                "verbose_name": "Réponse utilisateur",
                "verbose_name_plural": "Réponses utilisateurs",
            },
        ),
        migrations.AddField(
            model_name="question",
            name="quiz",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="questions", to="elearning.quiz"
            ),
        ),
        migrations.CreateModel(
            name="Commentaire",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("contenu", models.TextField()),
                (
                    "note",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
                (
                    "cours",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="commentaires", to="elearning.cours"
                    ),
                ),
                (
                    "utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commentaires_cours",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Commentaire",
                "verbose_name_plural": "Commentaires",
                "ordering": ["-date_creation"],
            },
        ),
        migrations.AddField(
            model_name="choixreponse",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="choix", to="elearning.question"
            ),
        ),
        migrations.CreateModel(
            name="Inscription",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date_inscription", models.DateTimeField(auto_now_add=True)),
                (
                    "progression",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("est_complete", models.BooleanField(default=False)),
                ("date_completion", models.DateTimeField(blank=True, null=True)),
                ("a_assiste_livestream", models.BooleanField(default=False)),
                (
                    "cours",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="inscriptions", to="elearning.cours"
                    ),
                ),
                (
                    "utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Inscription",
                "verbose_name_plural": "Inscriptions",
                "ordering": ["-date_inscription"],
                "unique_together": {("utilisateur", "cours")},
            },
        ),
    ]
