# Generated by Django 4.2.7 on 2026-02-28 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('type_document', models.CharField(choices=[('COMPTE_EXPLOITATION', "Compte d'Exploitation Prévisionnel"), ('ITINERAIRE_TECHNIQUE', 'Itinéraire Technique')], max_length=50, verbose_name='Type de document')),
                ('format_fichier', models.CharField(choices=[('EXCEL', 'Excel'), ('WORD', 'Word')], max_length=10, verbose_name='Format')),
                ('fichier_template', models.FileField(upload_to='templates/', verbose_name='Fichier template')),
                ('variables_requises', models.JSONField(default=list, verbose_name='Variables requises')),
                ('version', models.IntegerField(default=1, verbose_name='Version')),
            ],
            options={
                'verbose_name': 'Template de document',
                'verbose_name_plural': 'Templates de documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentTechnique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix (FCFA)')),
                ('culture', models.CharField(max_length=100, verbose_name='Culture')),
                ('fichier_genere', models.FileField(upload_to='documents/', verbose_name='Fichier généré')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('canton', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='locations.canton', verbose_name='Canton')),
                ('prefecture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='locations.prefecture', verbose_name='Préfecture')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='locations.region', verbose_name='Région')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='documents.documenttemplate', verbose_name='Template')),
            ],
            options={
                'verbose_name': 'Document technique',
                'verbose_name_plural': 'Documents techniques',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['culture', 'canton'], name='documents_d_culture_dd43a2_idx'), models.Index(fields=['actif'], name='documents_d_actif_90755f_idx')],
            },
        ),
    ]
