# Generated by Django 5.2.11 on 2026-03-01 09:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AchatDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('lien_telechargement', models.CharField(blank=True, max_length=500, verbose_name='Lien de téléchargement')),
                ('expiration_lien', models.DateTimeField(blank=True, null=True, verbose_name='Expiration du lien')),
                ('nombre_telechargements', models.IntegerField(default=0, verbose_name='Nombre de téléchargements')),
                ('acheteur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Acheteur')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='documents.documenttechnique', verbose_name='Document')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='payments.transaction', verbose_name='Transaction')),
            ],
            options={
                'verbose_name': 'Achat de document',
                'verbose_name_plural': 'Achats de documents',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['acheteur', 'created_at'], name='documents_a_acheteu_8ba12e_idx')],
            },
        ),
    ]
