# Generated by Django 5.2.11 on 2026-03-01 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_achatdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('ip_address', models.GenericIPAddressField(verbose_name='Adresse IP')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Horodatage')),
                ('achat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='documents.achatdocument', verbose_name='Achat')),
            ],
            options={
                'verbose_name': 'Log de téléchargement',
                'verbose_name_plural': 'Logs de téléchargement',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['achat', 'timestamp'], name='documents_d_achat_i_cd3784_idx')],
            },
        ),
    ]
