# Generated by Django 5.2.11 on 2026-03-01 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataRetentionPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.CharField(choices=[('TRANSACTION', 'Données de transaction'), ('USER_DATA', 'Données utilisateur'), ('LOGS', 'Logs système'), ('DOCUMENTS', 'Documents')], max_length=20, unique=True, verbose_name='Type de données')),
                ('retention_period_days', models.IntegerField(help_text='Nombre de jours de conservation des données', verbose_name='Période de rétention (jours)')),
                ('description', models.TextField(help_text='Description de la politique de rétention', verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': 'Politique de rétention',
                'verbose_name_plural': 'Politiques de rétention',
                'ordering': ['data_type'],
            },
        ),
        migrations.CreateModel(
            name='AccountDeletionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('reason', models.TextField(blank=True, help_text='Raison de la suppression (optionnel)', verbose_name='Raison')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('PROCESSING', 'En cours de traitement'), ('COMPLETED', 'Terminée'), ('CANCELLED', 'Annulée')], default='PENDING', max_length=20, verbose_name='Statut')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de demande')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de traitement')),
                ('data_export_file', models.FileField(blank=True, null=True, upload_to='data_exports/%Y/%m/', verbose_name="Fichier d'export des données")),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_deletions', to=settings.AUTH_USER_MODEL, verbose_name='Traité par')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deletion_requests', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Demande de suppression',
                'verbose_name_plural': 'Demandes de suppression',
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='compliance__user_id_8ef92e_idx'), models.Index(fields=['requested_at'], name='compliance__request_1f8399_idx')],
            },
        ),
        migrations.CreateModel(
            name='CGUAcceptance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('version_cgu', models.CharField(help_text='Version des CGU acceptées (ex: 1.0, 1.1)', max_length=20, verbose_name='Version des CGU')),
                ('ip_address', models.GenericIPAddressField(help_text="Adresse IP lors de l'acceptation", verbose_name='Adresse IP')),
                ('user_agent', models.TextField(help_text='User agent du navigateur', verbose_name='User Agent')),
                ('accepted_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'acceptation")),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cgu_acceptances', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Acceptation CGU',
                'verbose_name_plural': 'Acceptations CGU',
                'ordering': ['-accepted_at'],
                'indexes': [models.Index(fields=['user', 'accepted_at'], name='compliance__user_id_efcce4_idx')],
            },
        ),
        migrations.CreateModel(
            name='ElectronicReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('receipt_number', models.CharField(help_text='Numéro unique du reçu (ex: REC-2024-00001)', max_length=50, unique=True, verbose_name='Numéro de reçu')),
                ('buyer_name', models.CharField(max_length=200, verbose_name="Nom de l'acheteur")),
                ('buyer_phone', models.CharField(max_length=15, verbose_name="Téléphone de l'acheteur")),
                ('description', models.TextField(help_text='Description de la transaction', verbose_name='Description')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant (FCFA)')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Montant TVA (FCFA)')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant total (FCFA)')),
                ('issued_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'émission")),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='receipts/%Y/%m/', verbose_name='Fichier PDF')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='receipt', to='payments.transaction', verbose_name='Transaction')),
            ],
            options={
                'verbose_name': 'Reçu électronique',
                'verbose_name_plural': 'Reçus électroniques',
                'ordering': ['-issued_at'],
                'indexes': [models.Index(fields=['receipt_number'], name='compliance__receipt_be0df0_idx'), models.Index(fields=['issued_at'], name='compliance__issued__94ccbf_idx')],
            },
        ),
    ]
