# Generated by Django 4.2.7 on 2026-02-28 23:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_transaction', models.CharField(choices=[('ACHAT_DOCUMENT', 'Achat Document'), ('RECRUTEMENT_AGRONOME', 'Recrutement Agronome'), ('PREVENTE', 'Prévente Agricole'), ('TRANSPORT', 'Transport'), ('ABONNEMENT', 'Abonnement Premium')], max_length=30, verbose_name='Type')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant (FCFA)')),
                ('commission_plateforme', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Commission')),
                ('statut', models.CharField(choices=[('PENDING', 'En Attente'), ('SUCCESS', 'Réussie'), ('FAILED', 'Échouée'), ('REFUNDED', 'Remboursée')], default='PENDING', max_length=20, verbose_name='Statut')),
                ('fedapay_transaction_id', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='ID Fedapay')),
                ('reference_externe', models.CharField(blank=True, max_length=100, null=True, verbose_name='Référence externe')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['utilisateur', 'created_at'], name='payments_tr_utilisa_e7317d_idx'), models.Index(fields=['statut'], name='payments_tr_statut_7ec9f7_idx')],
            },
        ),
    ]
