# Generated by Django 5.2.11 on 2026-03-01 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EscrowAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('montant_bloque', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant bloqué (FCFA)')),
                ('statut', models.CharField(choices=[('BLOQUE', 'Bloqué'), ('LIBERE', 'Libéré'), ('REMBOURSE', 'Remboursé')], default='BLOQUE', max_length=20, verbose_name='Statut')),
                ('date_liberation_prevue', models.DateTimeField(verbose_name='Date de libération prévue')),
                ('date_liberation_effective', models.DateTimeField(blank=True, null=True, verbose_name='Date de libération effective')),
                ('beneficiaire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='escrow_beneficiaire', to=settings.AUTH_USER_MODEL, verbose_name='Bénéficiaire')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payments.transaction', verbose_name='Transaction')),
            ],
            options={
                'verbose_name': 'Compte Escrow',
                'verbose_name_plural': 'Comptes Escrow',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['statut', 'date_liberation_prevue'], name='payments_es_statut_aa98ad_idx'), models.Index(fields=['beneficiaire', 'statut'], name='payments_es_benefic_57396a_idx')],
            },
        ),
    ]
