# Generated by Django 5.2.11 on 2026-03-01 08:02

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcheteurProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_acheteur', models.CharField(choices=[('PARTICULIER', 'Particulier'), ('ENTREPRISE', 'Entreprise'), ('COOPERATIVE', 'Coopérative'), ('EXPORTATEUR', 'Exportateur')], default='PARTICULIER', max_length=20, verbose_name="Type d'acheteur")),
                ('volume_achats_annuel', models.DecimalField(blank=True, decimal_places=2, help_text="Volume d'achats annuel estimé en tonnes", max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name="Volume d'achats annuel (tonnes)")),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='acheteur_profile', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Profil Acheteur',
                'verbose_name_plural': 'Profils Acheteurs',
            },
        ),
        migrations.CreateModel(
            name='InstitutionProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_organisme', models.CharField(max_length=200, verbose_name="Nom de l'organisme")),
                ('niveau_acces', models.CharField(choices=[('NATIONAL', 'National'), ('REGIONAL', 'Régional'), ('PREFECTORAL', 'Préfectoral')], max_length=20, verbose_name="Niveau d'accès")),
                ('regions_acces', models.ManyToManyField(blank=True, help_text="Régions auxquelles l'institution a accès (vide = toutes)", to='locations.region', verbose_name="Régions d'accès")),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='institution_profile', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Profil Institution',
                'verbose_name_plural': 'Profils Institutions',
            },
        ),
        migrations.CreateModel(
            name='OuvrierProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competences', models.JSONField(default=list, help_text='Liste des compétences agricoles', verbose_name='Compétences')),
                ('note_moyenne', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Note moyenne')),
                ('nombre_avis', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name="Nombre d'avis")),
                ('disponible', models.BooleanField(default=True, verbose_name='Disponible')),
                ('cantons_disponibles', models.ManyToManyField(blank=True, related_name='ouvriers_disponibles', to='locations.canton', verbose_name='Cantons disponibles')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ouvrier_profile', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Profil Ouvrier',
                'verbose_name_plural': 'Profils Ouvriers',
            },
        ),
        migrations.CreateModel(
            name='AgronomeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialisations', models.JSONField(default=list, help_text='Liste des spécialisations agricoles', verbose_name='Spécialisations')),
                ('statut_validation', models.CharField(choices=[('EN_ATTENTE', 'En Attente de Validation'), ('VALIDE', 'Validé'), ('REJETE', 'Rejeté')], default='EN_ATTENTE', max_length=20, verbose_name='Statut de validation')),
                ('badge_valide', models.BooleanField(default=False, verbose_name='Badge validé')),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation')),
                ('note_moyenne', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Note moyenne')),
                ('nombre_avis', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name="Nombre d'avis")),
                ('canton_rattachement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locations.canton', verbose_name='Canton de rattachement')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agronome_profile', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Profil Agronome',
                'verbose_name_plural': 'Profils Agronomes',
                'indexes': [models.Index(fields=['statut_validation', 'canton_rattachement'], name='users_agron_statut__d512e0_idx')],
            },
        ),
        migrations.CreateModel(
            name='ExploitantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('superficie_totale', models.DecimalField(decimal_places=2, help_text="Superficie totale de l'exploitation en hectares", max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Superficie totale (hectares)')),
                ('coordonnees_gps', models.JSONField(help_text='Format: {"lat": latitude, "lon": longitude}', verbose_name='Coordonnées GPS')),
                ('statut_verification', models.CharField(choices=[('NON_VERIFIE', 'Non Vérifié'), ('EN_ATTENTE', 'En Attente de Vérification'), ('VERIFIE', 'Vérifié'), ('REJETE', 'Rejeté')], default='NON_VERIFIE', max_length=20, verbose_name='Statut de vérification')),
                ('date_verification', models.DateTimeField(blank=True, null=True, verbose_name='Date de vérification')),
                ('cultures_actuelles', models.JSONField(default=list, help_text='Liste des cultures actuellement cultivées', verbose_name='Cultures actuelles')),
                ('canton_principal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locations.canton', verbose_name='Canton principal')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exploitant_profile', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Profil Exploitant',
                'verbose_name_plural': 'Profils Exploitants',
                'indexes': [models.Index(fields=['statut_verification'], name='users_explo_statut__0c1b89_idx')],
            },
        ),
    ]
