# Generated by Django 5.2.11 on 2026-03-01 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_add_two_factor_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='agronomeprofile',
            name='motif_rejet',
            field=models.TextField(blank=True, help_text='Raison du rejet de la demande de validation', null=True, verbose_name='Motif de rejet'),
        ),
        migrations.CreateModel(
            name='DocumentJustificatif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(choices=[('DIPLOME', 'Diplôme'), ('CERTIFICATION', 'Certification'), ('PIECE_IDENTITE', "Pièce d'identité"), ('AUTRE', 'Autre')], max_length=20, verbose_name='Type de document')),
                ('fichier', models.FileField(upload_to='agronomists/justificatifs/', verbose_name='Fichier')),
                ('nom_fichier', models.CharField(max_length=255, verbose_name='Nom du fichier')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'upload")),
                ('agronome_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents_justificatifs', to='users.agronomeprofile', verbose_name='Profil agronome')),
            ],
            options={
                'verbose_name': 'Document Justificatif',
                'verbose_name_plural': 'Documents Justificatifs',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
