# Generated by Django 4.2.7 on 2026-03-03 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_exploitantprofile_motif_rejet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='Numéro de téléphone'),
        ),
    ]
