# Generated by Django 4.2.7 on 2026-03-07 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_add_performance_indexes"),
        ("users", "0008_user_email_verified"),
    ]

    operations = []
