# Generated by Django 4.2.7 on 2026-03-07 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_merge_20260307_0114"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="agronomeprofile",
            name="idx_agro_validated",
        ),
        migrations.RemoveIndex(
            model_name="documentjustificatif",
            name="idx_doc_type",
        ),
        migrations.RemoveIndex(
            model_name="documentjustificatif",
            name="idx_doc_user_type",
        ),
        migrations.RemoveIndex(
            model_name="exploitantprofile",
            name="idx_expl_verified",
        ),
        migrations.RemoveIndex(
            model_name="farmverificationdocument",
            name="idx_farm_user",
        ),
        migrations.RemoveIndex(
            model_name="user",
            name="idx_user_email",
        ),
        migrations.RemoveIndex(
            model_name="user",
            name="idx_user_phone",
        ),
        migrations.RemoveIndex(
            model_name="user",
            name="idx_user_type",
        ),
        migrations.RemoveIndex(
            model_name="user",
            name="idx_user_active",
        ),
        migrations.RemoveIndex(
            model_name="user",
            name="idx_user_created",
        ),
        migrations.RemoveIndex(
            model_name="user",
            name="idx_user_type_active",
        ),
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("EXPLOITANT", "Exploitant"),
                    ("AGRONOME", "Agronome"),
                    ("OUVRIER", "Ouvrier Agricole"),
                    ("ACHETEUR", "Acheteur"),
                    ("INSTITUTION", "Institution"),
                    ("ADMIN", "Administrateur"),
                ],
                default="",
                max_length=20,
                verbose_name="Type d'utilisateur",
            ),
        ),
    ]
