# Generated by Django 4.2.7 on 2026-03-08 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0001_initial"),
        ("users", "0011_allow_empty_exploitant_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="acheteurprofile",
            name="canton",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="acheteurs",
                to="locations.canton",
                verbose_name="Canton",
            ),
        ),
        migrations.AddField(
            model_name="acheteurprofile",
            name="cantons_intervention",
            field=models.ManyToManyField(
                blank=True,
                help_text="Zones géographiques où l'acheteur intervient",
                related_name="acheteurs_actifs",
                to="locations.canton",
                verbose_name="Cantons d'intervention",
            ),
        ),
        migrations.AddField(
            model_name="acheteurprofile",
            name="prefecture",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="acheteurs",
                to="locations.prefecture",
                verbose_name="Préfecture",
            ),
        ),
        migrations.AddField(
            model_name="acheteurprofile",
            name="produits_interesses",
            field=models.JSONField(
                default=list,
                help_text="Liste des produits que l'acheteur souhaite acheter",
                verbose_name="Produits d'intérêt",
            ),
        ),
        migrations.AddField(
            model_name="acheteurprofile",
            name="profil_complet",
            field=models.BooleanField(
                default=False,
                help_text="Indique si le profil est complètement renseigné",
                verbose_name="Profil complet",
            ),
        ),
        migrations.AddField(
            model_name="acheteurprofile",
            name="region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="acheteurs",
                to="locations.region",
                verbose_name="Région",
            ),
        ),
        migrations.AddField(
            model_name="acheteurprofile",
            name="telephone",
            field=models.CharField(blank=True, max_length=20, verbose_name="Numéro de téléphone"),
        ),
    ]
