# Generated by Django 5.2.11 on 2026-03-01 18:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('description', models.TextField(verbose_name='Description')),
                ('budget_propose', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Budget proposé (FCFA)')),
                ('statut', models.CharField(choices=[('DEMANDE', 'Demande Envoyée'), ('ACCEPTEE', 'Acceptée'), ('REFUSEE', 'Refusée'), ('EN_COURS', 'En Cours'), ('TERMINEE', 'Terminée'), ('ANNULEE', 'Annulée')], default='DEMANDE', max_length=20, verbose_name='Statut')),
                ('date_debut', models.DateField(blank=True, null=True, verbose_name='Date de début')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('agronome', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='missions_recues', to=settings.AUTH_USER_MODEL, verbose_name='Agronome')),
                ('exploitant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='missions_creees', to=settings.AUTH_USER_MODEL, verbose_name='Exploitant')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='payments.transaction', verbose_name='Transaction')),
            ],
            options={
                'verbose_name': 'Mission',
                'verbose_name_plural': 'Missions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['exploitant', 'statut'], name='missions_mi_exploit_5c06f7_idx'), models.Index(fields=['agronome', 'statut'], name='missions_mi_agronom_ab4819_idx')],
            },
        ),
    ]
