# Generated by Django 4.2.7

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0012_acheteurprofile_canton_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('card_number', models.CharField(max_length=20, unique=True, verbose_name='Numéro de carte')),
                ('card_type', models.CharField(
                    choices=[
                        ('OUVRIER', 'Ouvrier Agricole'),
                        ('ACHETEUR', 'Acheteur / Commerce'),
                        ('AGRONOME', 'Ingénieur Agronome'),
                    ],
                    max_length=20
                )),
                ('statut', models.CharField(
                    choices=[
                        ('active', 'Active'),
                        ('expired', 'Expirée'),
                        ('revoked', 'Révoquée'),
                    ],
                    default='active',
                    max_length=20
                )),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('ouvrier', models.OneToOneField(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='card',
                    to='users.ouvrierprofile'
                )),
                ('acheteur', models.OneToOneField(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='card',
                    to='users.acheteurprofile'
                )),
                ('agronome', models.OneToOneField(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='card',
                    to='users.agronomeprofile'
                )),
            ],
            options={
                'verbose_name': 'Carte Professionnelle',
                'verbose_name_plural': 'Cartes Professionnelles',
                'ordering': ['-created_at'],
            },
        ),
    ]
