# Generated by Django 4.2.7 on 2026-03-03 23:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0002_escrowaccount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreventeAgricole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('culture', models.CharField(max_length=100, verbose_name='Culture')),
                ('quantite_estimee', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantité estimée (tonnes)')),
                ('date_recolte_prevue', models.DateField(verbose_name='Date de récolte prévue')),
                ('prix_par_tonne', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix par tonne (FCFA)')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('statut', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('ENGAGEE', 'Engagée'), ('LIVREE', 'Livrée'), ('ANNULEE', 'Annulée')], default='DISPONIBLE', max_length=20, verbose_name='Statut')),
                ('canton_production', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locations.canton', verbose_name='Canton de production')),
                ('exploitant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preventes', to=settings.AUTH_USER_MODEL, verbose_name='Exploitant')),
            ],
            options={
                'verbose_name': 'Prévente Agricole',
                'verbose_name_plural': 'Préventes Agricoles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EngagementPrevente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('quantite_engagee', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantité engagée')),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant total')),
                ('acompte_20', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Acompte (20%)')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En Attente'), ('ACOMPTE_PAYE', 'Acompte Payé'), ('LIVRAISON_CONFIRMEE', 'Livraison Confirmée'), ('PAIEMENT_COMPLET', 'Paiement Complet'), ('ANNULE', 'Annulé')], default='EN_ATTENTE', max_length=20, verbose_name='Statut')),
                ('date_livraison', models.DateField(blank=True, null=True, verbose_name='Date de livraison')),
                ('acheteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagements_acheteur', to=settings.AUTH_USER_MODEL, verbose_name='Acheteur')),
                ('prevente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='engagements', to='presales.preventeagricole', verbose_name='Prévente')),
                ('transaction_acompte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='payments.transaction', verbose_name="Transaction d'acompte")),
            ],
            options={
                'verbose_name': 'Engagement de Prévente',
                'verbose_name_plural': 'Engagements de Prévente',
                'ordering': ['-created_at'],
            },
        ),
    ]
