# Generated by Django 5.2.11 on 2026-03-01 21:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('missions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('note_valeur', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Note (1-5 étoiles)')),
                ('commentaire', models.TextField(validators=[django.core.validators.MinLengthValidator(20)], verbose_name='Commentaire')),
                ('statut', models.CharField(choices=[('PUBLIE', 'Publié'), ('SIGNALE', 'Signalé'), ('MODERE', 'Modéré'), ('REJETE', 'Rejeté')], default='PUBLIE', max_length=20, verbose_name='Statut')),
                ('nombre_signalements', models.IntegerField(default=0, verbose_name='Nombre de signalements')),
                ('mission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notations', to='missions.mission', verbose_name='Mission')),
                ('notateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notations_donnees', to=settings.AUTH_USER_MODEL, verbose_name='Notateur')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notations_recues', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur noté')),
            ],
            options={
                'verbose_name': 'Notation',
                'verbose_name_plural': 'Notations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SignalementNotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('motif', models.CharField(choices=[('INAPPROPRIE', 'Contenu inapproprié'), ('FAUX', 'Information fausse'), ('SPAM', 'Spam'), ('HARCÈLEMENT', 'Harcèlement'), ('AUTRE', 'Autre')], max_length=20, verbose_name='Motif')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('traite', models.BooleanField(default=False, verbose_name='Traité')),
                ('notation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signalements', to='ratings.notation', verbose_name='Notation')),
                ('signaleur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='signalements_effectues', to=settings.AUTH_USER_MODEL, verbose_name='Signaleur')),
            ],
            options={
                'verbose_name': 'Signalement de notation',
                'verbose_name_plural': 'Signalements de notations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='notation',
            index=models.Index(fields=['note', 'statut'], name='ratings_not_note_id_676774_idx'),
        ),
        migrations.AddIndex(
            model_name='notation',
            index=models.Index(fields=['notateur'], name='ratings_not_notateu_783f68_idx'),
        ),
        migrations.AddIndex(
            model_name='notation',
            index=models.Index(fields=['mission'], name='ratings_not_mission_59bdf7_idx'),
        ),
        migrations.AddIndex(
            model_name='notation',
            index=models.Index(fields=['-created_at'], name='ratings_not_created_bc871b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='notation',
            unique_together={('notateur', 'mission')},
        ),
        migrations.AlterUniqueTogether(
            name='signalementnotation',
            unique_together={('notation', 'signaleur')},
        ),
    ]
