# Generated by Django 4.2.7 on 2026-03-03 23:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PreferenceNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nouveau_message_email', models.BooleanField(default=True)),
                ('mission_acceptee_email', models.BooleanField(default=True)),
                ('paiement_recu_email', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences_notification', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('type_notification', models.CharField(choices=[('NOUVEAU_MESSAGE', 'Nouveau message'), ('MISSION_ACCEPTEE', 'Mission acceptée'), ('MISSION_REFUSEE', 'Mission refusée'), ('PAIEMENT_RECU', 'Paiement reçu'), ('AVIS_RECU', 'Avis reçu'), ('CONTRAT_SIGNE', 'Contrat signé'), ('PREVENTE_ENGAGEE', 'Prévente engagée'), ('ALERTE_SYSTEME', 'Alerte système')], max_length=30)),
                ('titre', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('lien', models.CharField(blank=True, max_length=500, null=True)),
                ('lue', models.BooleanField(default=False)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
